# Generated by Django 5.1.7 on 2026-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_api', '0005_languagedubbing'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessing',
            name='crop_to_portrait',
            field=models.BooleanField(default=True),
        ),
    ]
